import { FC } from "react";
import { Image } from "../../../../components";
import { Card, Container } from "./styles";
 
const FooterContent: FC = () => {
    return (
        <Container>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Rodrigo</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Fabiane</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Adri</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
            <Card>
                <div>
                    <Image 
                        url="https://avatars.githubusercontent.com/u/29779941?v=4"
                        name="avatar"    
                    />
                    <h1>5</h1>
                </div>
                <strong>Caio</strong>
            </Card>
        </Container>
    );
}
 
export default FooterContent;