import { FC } from "react";
import { Image } from "../../../../components";
import { Card, Container } from "./styles";
 
const MainContent: FC = () => {
    return (
        <Container>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
            <Card>
            <Image 
                url="https://avatars.githubusercontent.com/u/29779941?v=4"
                name="avatar"    
            />
            <h1>5</h1>
            </Card>
        </Container>
    );
}
 
export default MainContent;